### ISSUE TITLE
writer.addTriples is not a function

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/LDPjs#3]
```
2019-05-09T23:19:54.632581+00:00 app[web.1]: GET /r/
2019-05-09T23:19:54.632702+00:00 app[web.1]: db.get
2019-05-09T23:19:54.635948+00:00 app[web.1]: { _id:
2019-05-09T23:19:54.635950+00:00 app[web.1]: ObjectID {
2019-05-09T23:19:54.635952+00:00 app[web.1]: _bsontype: 'ObjectID',
2019-05-09T23:19:54.635953+00:00 app[web.1]: id:
2019-05-09T23:19:54.635955+00:00 app[web.1]: Buffer [Uint8Array] [ 92, 212, 181, 137, 241, 193, 130, 4, 233, 215, 61, 9 ] },
2019-05-09T23:19:54.635956+00:00 app[web.1]: name: 'http://0.0.0.0:3000/r/',
2019-05-09T23:19:54.635960+00:00 app[web.1]: interactionModel: 'http://www.w3.org/ns/ldp#BasicContainer',
2019-05-09T23:19:54.635962+00:00 app[web.1]: triples:
2019-05-09T23:19:54.635963+00:00 app[web.1]: [ { subject: 'http://0.0.0.0:3000/r/',
2019-05-09T23:19:54.635965+00:00 app[web.1]: predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
2019-05-09T23:19:54.635967+00:00 app[web.1]: object: 'http://www.w3.org/ns/ldp#Resource' },
2019-05-09T23:19:54.635968+00:00 app[web.1]: { subject: 'http://0.0.0.0:3000/r/',
2019-05-09T23:19:54.635969+00:00 app[web.1]: predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
2019-05-09T23:19:54.635971+00:00 app[web.1]: object: 'http://www.w3.org/ns/ldp#RDFSource' },
2019-05-09T23:19:54.635972+00:00 app[web.1]: { subject: 'http://0.0.0.0:3000/r/',
2019-05-09T23:19:54.635974+00:00 app[web.1]: predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
2019-05-09T23:19:54.635976+00:00 app[web.1]: object: 'http://www.w3.org/ns/ldp#Container' },
2019-05-09T23:19:54.635977+00:00 app[web.1]: { subject: 'http://0.0.0.0:3000/r/',
2019-05-09T23:19:54.635979+00:00 app[web.1]: predicate: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
2019-05-09T23:19:54.635981+00:00 app[web.1]: object: 'http://www.w3.org/ns/ldp#BasicContainer' },
2019-05-09T23:19:54.635982+00:00 app[web.1]: { subject: 'http://0.0.0.0:3000/r/',
2019-05-09T23:19:54.635983+00:00 app[web.1]: predicate: 'http://purl.org/dc/terms/title',
2019-05-09T23:19:54.635985+00:00 app[web.1]: object: '"LDP.js root container"' } ],
2019-05-09T23:19:54.635986+00:00 app[web.1]: deleted: false }
2019-05-09T23:19:54.641939+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:132
2019-05-09T23:19:54.641941+00:00 app[web.1]: throw err;
2019-05-09T23:19:54.641943+00:00 app[web.1]: ^
2019-05-09T23:19:54.641944+00:00 app[web.1]:
2019-05-09T23:19:54.641945+00:00 app[web.1]: TypeError: writer.addTriples is not a function
2019-05-09T23:19:54.641946+00:00 app[web.1]: at exports.serialize (/app/turtle.js:37:9)
2019-05-09T23:19:54.641947+00:00 app[web.1]: at /app/service.js:102:5
2019-05-09T23:19:54.641948+00:00 app[web.1]: at /app/service.js:684:5
2019-05-09T23:19:54.641950+00:00 app[web.1]: at /app/db.js:191:3
2019-05-09T23:19:54.641951+00:00 app[web.1]: at result (/app/node_modules/mongodb/lib/utils.js:414:17)
2019-05-09T23:19:54.641952+00:00 app[web.1]: at executeCallback (/app/node_modules/mongodb/lib/utils.js:406:9)
2019-05-09T23:19:54.641954+00:00 app[web.1]: at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55)
2019-05-09T23:19:54.641955+00:00 app[web.1]: at cursor.close (/app/node_modules/mongodb/lib/operations/cursor_ops.js:218:62)
2019-05-09T23:19:54.641956+00:00 app[web.1]: at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55)
2019-05-09T23:19:54.641957+00:00 app[web.1]: at completeClose (/app/node_modules/mongodb/lib/cursor.js:887:14)
```

**Comment by berezovskyi** [comment]
trying this impl out until https://github.com/OSLC/ldp-app/issues/7 is resolved.
